### ISSUE TITLE
Enrich event data

### ISSUE THREAD

**Issue by microwavekonijn** [microwavekonijn/ps2census#25]
- [ ] ~~`zone_id` for `MetagameEvent` can be computed~~;
- [x] ~~`is_suicide` for `Death` can be computed~~;
- [ ] ~~`is_teamkill` for `Death` can be computed~~;
- [x] Timestamps to Date;
- [x] Parse booleans;
- [x] `kill_type` for `Death` to determine if suicide or teamkill.

**Comment by Maelstromeous** [comment]
Don't forget `is_teamkill`, which is checking the class loadout IDs against their faction. Logic also must dictate the following for:

* `is_suicide` must have a check to see if the character IDs of `attacker_character_id` and `character_id` exactly match (don't forget BigInt issues)
* `is_teamkill` must have a check for class loadouts, comparing against a list of loadouts for the same faction, if both match, it's a TK. This must additionally check if the `is_suicide` flag is false.

**Comment by Maelstromeous** [comment]
If you're able to pass down the `attacker_faction_id` and `character_faction_id`s that would be most handy too!

**Comment by Maelstromeous** [comment]
`Timestamps to Date;` Wouldn't fully recommend this, lots of apps will want this in UTC and then convert it as they will.

**Comment by microwavekonijn** [comment]
How do you mean? I want to convert it to the default Date class of js.

**Comment by Maelstromeous** [comment]
Nothing against a date, although I for example prefer to use UTC timestamps as it's universal across the board, then convert it at the application layer should I need to.

**Comment by microwavekonijn** [comment]
Could do, but most date libraries like moment.js and date-fns use the date object. Besides with this I try to eliminate most of the quirks of the Census API, event he straight forward ones.
