### ISSUE TITLE
CharacterManager caches invalid responses

### ISSUE THREAD

**Issue by Maelstromeous** [microwavekonijn/ps2census#30]
Currently the CharacterManager is caching invalid character responses.

Scenario:

Brand new player is requested from Census, world ID is missing (BR 0). CharacterManager considers this a valid response (it currently isn't able to detect if a response is invalid in that manner) and continues to serve an invalid response.

**Comment by microwavekonijn** [comment]
I don't think it is possible to verify this, as it depends on the request object. It also means that whatever you do it requires more logic, which is not necessarily a good thing.
