### ISSUE TITLE
Bug - TypeError: Client is not a constructor

### ISSUE THREAD

**Issue by dbrennand** [microwavekonijn/ps2census#45]
Hi,

I just ran into an issue with the new version where the following error occurs: `TypeError: Client is not a constructor`.

Looking at [`census.client.ts`](https://github.com/microwavekonijn/ps2census/blob/master/src/client/census.client.ts) the export class is in fact `CensusClient`.

I fixed this issue by doing the following:

```javascript
import census from 'ps2census';
const { CensusClient, Events } = census;

const subscriptions = [{
    // Connery, Miller, Cobalt, Emerald, SolTech
    worlds: ['1', '10', '13', '17', '40'],
    characters: ['all'],
    eventNames: ['MetagameEvent'],
    logicalAndCharactersWithWorlds: true,
}];

// Initalise ps2census event stream client
const client = new CensusClient(serviceID, 'ps2', {
    streamManager: {subscriptions}
});
```

**Comment by microwavekonijn** [comment]
I forgot to update the examples again. As there are now 2 clients I renamed the Stream client to avoid conflict.

**Comment by dbrennand** [comment]
I can submit a PR if you would like to fix the README example 😃
