### ISSUE TITLE
Faking events documentation changes

### ISSUE THREAD

**Issue by dbrennand** [microwavekonijn/ps2census#47]
The faking events documentation is outdated. 

The example uses the old `Client` constructor and the fake event is missing the `zone_id`.

**Comment by microwavekonijn** [comment]
Yeah, the docs are also outdated, same as the example. Though `zone_id` is not part of the `MetagameEvent` stream event as far as I know.

**Comment by dbrennand** [comment]
I'm using [`zone_id`](https://github.com/dbrennand/PS2Alert.me/blob/v1/backend/consumer/consumer.mjs#L58) from the `MetagameEvent` stream event in my project. I will make a quick PR to update it :-)

**Comment by microwavekonijn** [comment]
Okay, this has been fixed apparently. Needs to be added to the `MetagameEvent` class as well.

https://github.com/cooltrain7/Planetside-2-API-Tracker/issues/8

**Comment by dbrennand** [comment]
> 
> 
> Okay, this has been fixed apparently. Needs to be added to the `MetagameEvent` class as well.
> 
> [cooltrain7/Planetside-2-API-Tracker#8](https://github.com/cooltrain7/Planetside-2-API-Tracker/issues/8)

Ok. That's slightly out of scope of this PR. I will create a new issue to track adding `zone_id` to the `MetagameEvent` class.
