### ISSUE TITLE
Add zone_id to MetagameEvent class

### ISSUE THREAD

**Issue by dbrennand** [microwavekonijn/ps2census#51]
The [`MetagameEvent`](https://github.com/microwavekonijn/ps2census/blob/master/src/client/events/metagame.event.ts#L4) class is missing the `zone_id`.

See [issue 47 comment](https://github.com/microwavekonijn/ps2census/issues/47#issuecomment-890332110) for context.

**Comment by microwavekonijn** [comment]
Added v3.1.0
