### ISSUE TITLE
Fix test.ts due to websocket cert expiry

### ISSUE THREAD

**Issue by dbrennand** [microwavekonijn/ps2census#66]
The `test.ts` file needs fixing for the websocket certificate expiring.

**Comment by microwavekonijn** [comment]
You forgot to make a PR, and I didn't see the commit. It is fixed now.

**Comment by dbrennand** [comment]
Hi 👋🏻 Yes sorry I didn't have enough time to submit the PR. Glad it's fixed now though 🙂👍
