### ISSUE TITLE
Comparing multiple websocket connections through different proxies

### ISSUE THREAD

**Issue by brakenium** [microwavekonijn/ps2census#69]
Some people have suggested running multiple websockets and comparing the events between them. The most reliable way (if not the only one) seems to be running them through different proxies. In order to not completely reinvent the wheel I thought perhaps I could add this as a feature to ps2 census instead. I won't promise to write such a feature, but I'll consider it if you wouldn't be opposed to merging a PR like that. So is there any chance that would be worth a consideration?

**Comment by microwavekonijn** [comment]
I will definitely consider it if it can be implemented using some sort of bridge so the client can be configured in a traditional way or in a redundant way. You probably also have to look if `ws` supports proxies or how it can be supported.

With that said, I am working on another project that will do exactly this and more. I will hopefully have more new on it this weekend. https://github.com/nanite-systems

**Comment by brakenium** [comment]
I would've done it by wrapping or in another way using the existing stream client. A couple or days ago I looked into ws and proxy support, which seemed possible by using a different http client with proxy support iirc.

Though if you're working with a different project that might do the same, I'll wait how that plays out

**Comment by microwavekonijn** [comment]
The Nanite System project is live now. https://nanite-systems.net/
